version: 2.1
orbs:
  flutter: circleci/flutter@1.1.0
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
      - run: sudo apt-get install npm
      - coveralls/upload
