
version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.3
  flutter: circleci/flutter@1.1.0
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
      - post-steps:
        - codecov/upload