version: '2.1'
orbs:
  codecov: codecov/codecov@3.1.1
  flutter: circleci/flutter@1.2.0
jobs:
  build-project:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test --coverage
workflows:
  upload-to-codecov:
    jobs:
      - build-project:
          post-steps:
            - codecov/upload