version: 2.1
orbs: 
  flutter: circleci/flutter@1.1.0
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
      - coveralls/upload
